apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth
    service: auth
spec:
  selector:
    app: auth
    service: auth
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP